Cake.Recipe/Content/paths.cake, Cake.Recipe/Content/testing.cake
Question: does it make sense to have both MS test and VS test? Should I remove cod for MS Test especially since the code for MS test doesn't have support for OpenCover and the new code for VS test does support OpenCover?
=> (GH-7) Add support for VS Test

Cake.Recipe/Content/addins.cake
Update Cake.Slack to latest, and Cake 0.18.0 compatible, version
=> Update Cake.Slack to latest version

Cake.Recipe/Content/addins.cake
Update Cake.Slack to latest, and Cake 0.18.0 compatible, version
=> Update Cake.Git to the latest version

Cake.Recipe/Content/addins.cake
=> (maint) Update Cake.Wyam to 0.17.0

Cake.Recipe/Content/build.cake
Follup up to #63. Use fixed URL, can be changed later to use parameter from environment variable.
=> Use fixed URL

docs/input/docs/usage/creating-release.md
Add documentation how to create a release using Cake.Recipe.
Fixes #71
=> (GH-71) Add documentation how to create a release

README.md
Adds a readme. Since I couldn't access the Appveyor settings, I didn't add the build badges yet.
=> (doc) Add readme

docs/input/blog/new-release.md, docs/input/docs/fundamentals/environment-variables.md, docs/input/docs/usage/creating-release.md
Some smaller documentation improvements:
* Link to environment variables page from create release page for the required environement variables
* Remove sample blog post.
=> (doc) Documentation improvements

Cake.Recipe/Content/build.cake, Cake.Recipe/Content/paths.cake, Cake.Recipe/Content/testing.cake
=> Adding Fixie test runner.

Cake.Recipe/Content/paths.cake
Fixes #76 Everything works after making this correction, I have tested it across
several projects.
=> Fixing typo that got in.

docs/input/docs/fundamentals/environment-variables.md, docs/input/docs/usage/cleaning-cache.md
Add documentation how to clear AppVeyor cache
=> (doc) Add documentation how to clear AppVeyor cache

Cake.Recipe/Content/wyam.cake, build.cake
Only commit and push documentation changes if there are changes in the local repository.
=> Only commit and push if local changes exist

Cake.Recipe/Content/analyzing.cake, Cake.Recipe/Content/build.cake
Follow up to #93. Creates MsBuild code analysis reports even if build fails.
=> Create MsBuild code analysis reports even if build fails.

docs/input/docs/fundamentals/environment-variables.md, docs/input/docs/usage/cleaning-cache.md, docs/input/docs/usage/previewing-documentation.md, docs/input/docs/usage/publishing-documentation.md
Add documentation how to preview and manually publish documentation
=> Add documentation how to preview and manually publish documentation

Cake.Recipe/Content/build.cake
Ignore shared projects. Fixed #97
=> Ignore shproj

Cake.Recipe/Content/build.cake
Replacing library check with IsLibrary() parser extension
Use GetProjects() solution parser extension to filter solution folders
=> for cake-contrib/Cake.Recipe#66

docs/input/docs/fundamentals/environment-variables.md
Looking at the source for wyam.cake, I noticed it only looks at the last commit.
As such you'll probably want to to a rebase and merge through github instead of a normal merge.
I think that should work for the change to be picked up by the wyam publish task.
=> Added documentation for codecov env variable

Cake.Recipe/Content/build.cake, Cake.Recipe/Content/nuget.cake, Cake.Recipe/Content/parameters.cake, Cake.Recipe/Content/tasks.cake, Cake.Recipe/Content/testing.cake
The code have thus far not been tested on Linux and OSX (or travis to be exact).
Currently it's expected to fail on Linux/OSX during either build, or unit testing.
=> GH10: Implementing Support for .NET Core

Cake.Recipe/Content/build.cake, Cake.Recipe/Content/coveralls.cake, Cake.Recipe/Content/tasks.cake
=> GH109: Refactored Coverage Task to separate Coveralls task

Cake.Recipe/Cake.Recipe.nuspec
Add Cake contrib icon.
Fixes #120
=> GH120: Add Cake contrib icon

Cake.Recipe/Content/build.cake
=> (GH-126) Set version numbers during dotnet restore

Cake.Recipe/Content/build.cake, Cake.Recipe/Content/parameters.cake
Makes nuget restore sources configurable via parameter or NuGet.config file.
* fixes #138
=> GH138: Add NuGet Restore sources config

docs/input/docs/usage/getting-started-with-cake-recipe.md
Possibly related to https://github.com/cake-contrib/Cake.Recipe/issues/36
Written as a quickstart with a few hints for customising Cake.Recipe.
=> GH36: Add page for getting started with cake recipe.

.gitignore, setup.cake, test.cake
* fixes #140 
Example usage
```PowerShell
.\build.ps1 -Target 'Run-Integration-Tests' 
```
=> GH140: Add integration tests

Cake.Recipe/Content/parameters.cake, Cake.Recipe/Content/tasks.cake, Cake.Recipe/Content/testing.cake
This pull request is to satisfy issue #153
=> GH-153: Added Integration Testing Task

Cake.Recipe/Content/parameters.cake, Cake.Recipe/Content/testing.cake
To resolve issue #155 and fix bug introduced in #153 
Fixed issue with IntegrationTestScirptPath being null
Change ShouldRunIntegrationTests logic to look for file existence
=> (GH-155) Modified ShouldRunIntegrationTests logic

Cake.Recipe/Content/addins.cake, Cake.Recipe/Content/tools.cake
=> Update to Wyam 1.0.0

Cake.Recipe/Content/testing.cake
=> Fix for OpenCover

Cake.Recipe/Content/addins.cake, Cake.Recipe/Content/build.cake, Cake.Recipe/Content/paths.cake
This pull request is to resolve issue #157
=> (GH-157) Removed dependency on Cake.CodeAnalysisReporting

Cake.Recipe/Content/transifex.cake
Once again I found a typo in my code.
Somehow I used the MyDocuments folder path, while in reality it should have been the UserProfile folder path.
I hope I've gotten them all now.
=> Corrected path for transifex user settings

docs/input/docs/usage/code-coverage-reports.md
This pull request resolves issue #190
=> (GH-190) Added code coverage known issues document

Cake.Recipe/Content/addins.cake, Cake.Recipe/Content/tools.cake
As title, just a version bump to resolve an error running wyam
=> Updating wyam version to 1.2

Cake.Recipe/Content/addins.cake, Cake.Recipe/Content/tasks.cake, Cake.Recipe/Content/wyam.cake
=> #196 Upgrade to Cake.Graph 0.4.0 and switch to mermaid syntax

Cake.Recipe/Content/appveyor.cake, Cake.Recipe/Content/gitreleasemanager.cake, Cake.Recipe/Content/paths.cake
- Make sure all packages are uploaded to Appveyor and Github releases.
=> Adds generic packages directory.

Cake.Recipe/Content/build.cake
=> GH194: Fixing MSTest Issues

Cake.Recipe/Content/build.cake
=> GH200: Fix copying of NET SDK style library artifacts

docs/input/docs/usage/conventions.md
When I started using Cake.Recipe, I came up with a lot of questions and little things that prevented me from using it. Essentially, it was an understanding of current conventions and how to tweak them along with a perspective of the problem at hand and how to solve with this tool. Adding this note, to hopefully help the next person who comes along to learn.. This needs feedback
=> Document common Conventions and Steps

Cake.Recipe/Content/addins.cake
Update Cake.Figlet to 1.2.0 which is build against Cake 0.28.0
=> Update Cake.Figlet to 1.2.0

docs/input/docs/fundamentals/environment-variables.md
Add documentation for Chocolatey environment variables
=> Add documentation for Chocolatey environment variables

Cake.Recipe/Content/tools.cake
Update the codecov tool to the latest available version.
This tool have been tested to be working as expected in one of my addins:
[AppVeyor Log](https://ci.appveyor.com/project/cakecontrib/cake-codecov#L1278)
=> (GH-289) Updated codecov tool to 1.1.0

test.cake, tools/packages.config
=> (GH-304) Fixes integration tests

Cake.Recipe/Content/addins.cake, Cake.Recipe/Content/build.cake
=> Update Cake.Incubator to 3.1.0

Cake.Recipe/Content/gitversion.cake
While not exactly perfect (Best would have been to have this included already upstream), this is a workaround (hack) ta allow GitVersion (and Cake.Git) to work on Linux systems that is unable to load the native library included in the nupkg files).
fixes #354 
/CC @gep13 @pascalberger
=> (GH-354) Updated to patch LibGit2Sharp.dll.config

test.cake
=> Fix FileNotFound during integration tests due to renamed ".cake" file

Cake.Recipe/Content/credentials.cake, Cake.Recipe/Content/environment.cake, Cake.Recipe/Content/gitreleasemanager.cake, Cake.Recipe/Content/parameters.cake
=> Add support for 2FA to all methods in GitReleaseManager.cake

Cake.Recipe/Content/build.cake, Cake.Recipe/Content/parameters.cake
=> GH370: Adds RestorePackagesDirectory to BuildParameters

docs/input/docs/usage/issue-management.md
Add documentation for Cake.Issues.Recipe integration
=> Add Cake.Issues.Recipe documentation

Cake.Recipe/Content/addins.cake
Update Cake.Issues.Recipe to 0.3.1
Fixes #493
=> (GH-493) Update Cake.Issues.Recipe to 0.3.1

Cake.Recipe/Content/parameters.cake, Cake.Recipe/Content/wyam.cake
=> (GH-48) Made source files documentation conditional

Cake.Recipe/Content/gitversion.cake
=> (GH-506) Force lowercase sem versions on BuildVersion class creation

Cake.Recipe/Content/addins.cake
Update Cake.Issues.Recipe to 0.3.2 which adds support for reporting issues to Azure Pipelines (which will show 10 of the issues)
Fixes #516
=> Update to Cake.Issues.Recipe 0.3.2

Cake.Recipe/Content/build.cake, Cake.Recipe/Content/buildProvider.cake, Cake.Recipe/Content/tasks.cake, Cake.Recipe/Content/travis-ci.cake
First basic implementation of a build provider for Travis CI
fixes #60
may also be related to #188 and #259
=> (GH-60) Implemented build provider for Travis CI

Cake.Recipe/Content/packages.cake
This pull request adds symbol packaging support when using nuget pack.
It also updates dotnet pack to be more complete with the intention.
resolves #518
resolves #112
=> (GH-112, GH-518) Implement support for building source packages with nuget

Cake.Recipe/Content/build.cake, Cake.Recipe/Content/paths.cake, Cake.Recipe/Content/tasks.cake, Cake.Recipe/Content/testing.cake, Cake.Recipe/Content/toolsettings.cake
This pull request removes all support for the unit testing library/executable Fixie.
resolves #550
=> (GH-550) Removes support for unit test library fixie

Cake.Recipe/Content/build.cake, Cake.Recipe/Content/parameters.cake
This pull request adds the ability for users to disable deterministic builds if they do not want to make the necessary steps to fully enable such a build.
resolves #548
=> (GH-548) Add parameter to enable/disable deterministic builds

Cake.Recipe/Content/build.cake
This will result in the artifacts generated as part of the Issues build
to be uploaded as an artifact.
Fixes #62
=> (GH-62) Run Cake.Issues.Recipe entry task

.appveyor.yml, Cake.Recipe/Content/build.cake
Making it easier to remember, and type.
Fixes #555
=> (GH-555) Change name of entry task

Cake.Recipe/Content/addins.cake, Cake.Recipe/Content/analyzing.cake, Cake.Recipe/Content/toolsettings.cake
This will ultimately be replaced by new functionality in Cake.Issues.
Fixes #557
=> (GH-557) Remove usage of ReSharperReports

Cake.Recipe/Content/parameters.cake
=> (GH-559) Enable codecov by default

Cake.Recipe/Content/build.cake
This pull request adds support for logging the result of dotnet build to file.
Additionally this log file is passed to Cake.Issues so it can generate a issue report with the warning returned by msbuild.
resolves #568
=> (GH-568) Add support for logging when running .NET Core build

Cake.Recipe/Content/gitversion.cake, Cake.Recipe/Content/parameters.cake
Since this can be used when not using GitVersion.
Fixes #604
=> (GH-604) Rename shouldRunGitVersion parameter

Cake.Recipe/Content/toolsettings.cake
=> (GH-647) Fix typo in ToolSettings.NuGetTool value

docs/input/docs/known-issues/publishing-docs-on-gh-windows.md
As discussed with @AdmiringWorm documentation of this behaviour as a known issue.
=> (GH-680) Documentation of GH-680 as a known-issue.

docs/input/docs/fundamentals/print-parameters.md, docs/input/docs/fundamentals/set-parameters.md, docs/input/docs/upgrading/1.x-to-2.x.md, docs/input/docs/upgrading/index.cshtml
=> (GH-612) Add docs for upgrading to 2.0.0

Cake.Recipe/Content/parameters.cake
This commit adds the ability to detect wether we
are running on one of the supported branches even
in the cases where the current commit is a tag,
and it is not directly attached to a specific branch.
The changes made have been tested locally on both a detached tag, and on seperate branches associated with the tag.
**KNOWN PROBLEMS**: If the current branch is not 1 of the currently supported branches, and it is the current head of both the tag and one of the supported branches, then the supported branch will be used instead of 'Unknown'
fixes #708
=> (GH-708) Add ability to detect branches when running on detached tags

Cake.Recipe/Content/github-actions.cake, Cake.Recipe/Content/localbuild.cake, Cake.Recipe/Content/parameters.cake
to all cases of resolving "git" to make them work on windows.
=> (GH-738) added resolving of "git.exe"

docs/input/docs/ci-systems/appveyor.md, docs/input/docs/ci-systems/azure.md, docs/input/docs/ci-systems/github.md, docs/input/docs/ci-systems/travisci.md
additionally I fixed some of my typos and updated the Cake version on Azure and GH-Actions.
As discussed in #704, the installation of .NET Core is removed.
fixes #704
=> Updated the GitHub-Actions ci-page

.github/workflows/release-notes.yml
Need a deeper look, copied from Cake.Transifex.
Copied in a rush﻿
=> (maint) Add workflow for creating release notes

docs/input/docs/ci-systems/github.md
Also I documented the `skip_branch_with_pr` workaround.
fixes #753
=> (GH-753) added documentation of matrix builds in GitHub actions.

docs/input/docs/ci-systems/github.md
from local repository
fixes #809
=> (#809) removed the suppressing of PR builds

docs/input/docs/ci-systems/appveyor.md, docs/input/docs/ci-systems/azure.md, docs/input/docs/ci-systems/github.md, docs/input/docs/ci-systems/travisci.md
for GitHub Actions and Azure Pipelines.
Also added links to the respective documentations.
fixes #796
=> (#796) pinned virtual environments

Source/Cake.Recipe/Content/parameters.cake
both are now based on RepositoryName and no longer on title.
fixes #816
=> (#816) fixed AppVeyorProjectSlug and WebBaseEditUrl

Source/Cake.Recipe/Content/addins.cake, Source/Cake.Recipe/Content/build.cake, Source/Cake.Recipe/Content/credentials.cake, Source/Cake.Recipe/Content/email.cake, Source/Cake.Recipe/Content/environment.cake, Source/Cake.Recipe/Content/mastodon.cake, Source/Cake.Recipe/Content/microsoftteams.cake, Source/Cake.Recipe/Content/parameters.cake, Source/Cake.Recipe/Content/reporters.cake, Source/Cake.Recipe/Content/slack.cake, Source/Cake.Recipe/Content/twitter.cake, docs/input/docs/fundamentals/environment-variables.md, docs/input/docs/fundamentals/set-parameters.md, docs/input/docs/fundamentals/set-variable-names.md
This PR also adds a bit more flexibility in the success- and failure reporting.
(As mentioned in #950)
Fixes #510
=> (#510) post to mastodon on successful publishing
