- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/paths.cake
- Cake.Recipe/Content/tools.cake
Stores the MSBuild log as XML file in the build artifacts. Uses [XmlFileLogger](http://www.msbuildextensionpack.com/help/4.0.5.0/html/242ab4fd-c2e2-f6aa-325b-7588725aed24.htm) from [MSBuild Extension Pack](http://www.msbuildextensionpack.com/).
> (GH-58) Store build log in build artifacts

- Cake.Recipe/Content/build.cake
Adds support for restoring NuGet packages from the same MyGet feed packages are pushed to.
Btw. whats the reason for having https://www.myget.org/F/gep13/api/v2 there?
> Support restoring from the same MyGet feed packages are pushed to

- Cake.Recipe/Content/resharper.cake
- Cake.Recipe/Content/toolsettings.cake
Adds in additional properties to pass along to `DupFinderSettings`.
It may also be worth considering creating nested classes to start to delineate the various settings?  Just adding these new parameters + properties starts to feel messy.  If that's something that is desired, I could potentially re-work this PR to include it.
> GH-82: Extend DupFinder properties in ToolSettings

- Cake.Recipe/Content/addins.cake
- Cake.Recipe/Content/analyzing.cake
- Cake.Recipe/Content/paths.cake
Creates reports for MsBuild warnings using Cake.CodeAnalysisReporting.
Fixes #92
> (GH-92) Create reports for MsBuild warnings

- Cake.Recipe/Content/addins.cake
- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/parameters.cake
Can I get you all to have a quick look at this PR?  This starts to add in support for Dot Net Core Builds within Cake.Recipe.
It builds on a few assumptions:
* You will be using the built-in support for creating NuGet Packages (rather than requiring a NuSpec file)
* At the minute, it won't run Unit Tests/Coverage (this is waiting for an upstream addition to Cake.Incubator)
* The dependency graph is modified at run time, depending on whether the user calls `Build.Run` or `Build.RunDotNetCore`
I am open to any suggestions on what can be done differently here.
@pascalberger do you know what is required to support the Custom Logger that you added when using `DotNetCoreBuild`?
> Initial Support for Dot Net Core Builds

- Cake.Recipe/Content/addins.cake
- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/codecov.cake
- Cake.Recipe/Content/credentials.cake
- Cake.Recipe/Content/environment.cake
- Cake.Recipe/Content/gitversion.cake
- Cake.Recipe/Content/parameters.cake
- Cake.Recipe/Content/tasks.cake
- Cake.Recipe/Content/tools.cake
This PR implements the ability to upload coverage reports to codecov.
By default a coverage report is uploaded to codecov if the user doesn't disable the feature.
This should cause no problems for users with public repositories as a new codecov project is automatically created when the report is first pushed to codecov (although it may report an error on github the first time the report is published as there is no previous report to compare it with).
Noted as a WIP currently as there seem to be a bug where Cake.Codecov reports an error even when there isn't any (looking into it now).
This PR have been uploaded to my personal account, and can be tested by changing the load url in any supported cake addin using Cake.Recipe to https://www.myget.org/F/wormie-nugets/api/v2?package=Cake.Recipe …
> (GH-105) Added codecov report uploading

- Cake.Recipe/Content/build.cake
With this change both the DupFinder task and the InspecCode task will be ran after
the project have been built.
Fixes #108
> GH108: Fixed analyzers running before build

- Cake.Recipe/Content/analyzing.cake
Without the change in this PR only explorer would be opened in the incorrect location, and not the reports
itself.
fixes #51
> GH51: Updated analysers to open default program when viewing report file

- Cake.Recipe/Content/coveralls.cake
**NOTE:** This PR depends on the existing PR #114 .
That one needs to be merged first, and this then should be rebased afterwards.
fixes #106
> GH106: Changed Coverage Report task to a publish step

- Cake.Recipe/Content/tools.cake
Since GitLink 2.4.1 is deleted on nuget.org downgrade GitLink to latest stable release.
Fixes #122
> Downgrade GitLink to latest stable release

- Cake.Recipe/Content/build.cake
Use `dotnet publish` instead of just copying files for a .NET Core project when copying artifacts for an executable. Solves #121.
ping @gep13
> GH121: Use dotnet publish instead of just copying files for .NET Core

- Cake.Recipe/Content/gitversion.cake
- Cake.Recipe/Content/parameters.cake
Added a new property "IsPublicRepository" that is true by default.
The GitVersion configuration then looks at this property and adds the /NoFetch switch if it is a private repository and being accessed from AppVeyor.
This issue has a better explanation of what is the cause of the problem https://github.com/GitTools/GitVersion/issues/869
> Update GitVersion configuration to allow access to private repositories from AppVeyor.

- Cake.Recipe/Content/gitlink.cake
This PR changes the path passed to GitLink to be similar to the path passed to msbuild/dotnet utility.
fixes #129 
/cc @gep13
> GH129: Changed to use SolutionFilePath directory with GitLink

- Cake.Recipe/Content/parameters.cake
- Cake.Recipe/Content/testing.cake
This Pull Request is to resolve #132 
I attempted to solve two concerns.
1. An explicit path to the folder where the test are stored.  In the event that tests are not in the `"./src"` directory path.
2. Allow an override for the globber pattern in the event you want to execute only `"/**/*UnitTests.csproj"` and exclude `"/**/*IntegrationTests.csproj"`
> Added TestDirectoryPath and TestProjectPattern

- Cake.Recipe/Content/tools.cake
Fixes #145 - DupFinder and InspectCode tasks for not recognise V15.3 of Visual Studio and give warnings in log.
> GH145: Increase JetBrains.ReSharper.CommandLineTools version

- Cake.Recipe/Content/testing.cake
PR #162 applied these improvements when using xunit. This PR applies the same improvements to NUnit, VSTest, Fixie and DotNetCore-Test.
> Fix for OpenCover (for other unit testing platforms)

- Cake.Recipe/Content/testing.cake
I added the "-returntargetcode" to the OpenCoverSettings hoping it would solve #161. Unfortunately it doesn't solve the issue and also there was already a "-returntargetcode:0" parameter.
> Remove duplicate OpenCover parameter

- Cake.Recipe/Content/addins.cake
- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/credentials.cake
- Cake.Recipe/Content/environment.cake
- Cake.Recipe/Content/parameters.cake
- Cake.Recipe/Content/tasks.cake
- Cake.Recipe/Content/transifex.cake
Moved from the issue:
**TASKS**
- Will only be run if the following conditions are met
- Transifex support have been enabled explicitly, or implicitly if the following file exists in the repo `./.tx/config`
- A user settings file doesn't already exists (this will always be located in `%USERPROFILE%\.transifexrc` on windows, don't know on other platforms)
- If the transifex api credentials exists (by default will grab from the following environment variable `TRANSIFEX_API_TOKEN`)
- Will have no dependencies
- When it runs, it will create the user settings profile storing the specified api token.
- Will run if Transifex support have been enabled explicitly, or implicitly, and only if running on appveyor (or called explicitly)
- Will not check if the user settings file exists, if it doesn't …
> Adding support for transifex

- Cake.Recipe/Content/parameters.cake
- Cake.Recipe/Content/transifex.cake
This commit fixes the following:
Using an alias in methods where 'Context' isn't automatically available.
Missing Namespace for System.IO.Path.
Using a const variable when it isn't possible in that context.
@gep13 this is quite the priority, as Cake.Recipe won't compile at all until this is merged.
> Fixed a few build errors that happened after including transifex support

- Cake.Recipe/Content/toolsettings.cake
The current coverage filter includes everything `+[*]*` and then selectively excludes some namespaces such as `-[xunit.*]*` and `-[Cake.Core]*`. This can results in some namespaces to be inadvertently included because they haven't been specifically excluded.
A much better default value would be to include only the desired namespace and exclude unit tests. Like so: `+[MyCakeAddin*]* -[*.Tests]*`.
As a side effect, this new filter ensures that namespaces from 3rd party nuget packages (such as moq just to name one example) are not included, which is the root of the issue I discuss in #160.
> Improve default coverage filter

- Cake.Recipe/Content/toolsettings.cake
Remove hard-coded "Cake.Example.Tests" and replace with a more sensible default dupFinder exclude pattern.
Resolves #174
> More sensible default dupFinder exclude pattern

- Cake.Recipe/Content/analyzing.cake
- As DupFinder and InspectCode don't run on anything but Windows
> (GH-182) Added Windows Criteria

- Cake.Recipe/Content/build.cake
Check for IsVS2017ProjectFormat when doing publish, otherwise SDK style projects only targeting full framework won't be published using dotnet publish
> Check for IsVS2017ProjectFormat when doing publish

- Cake.Recipe/Content/nuget.cake
resolves https://github.com/cake-contrib/Cake.Recipe/issues/210
nb: I totally did this PR in the GitHub web editor and haven't tested it but it should be fine ;-)
If you could ship a new release ASAP after merging that would be ace cause this problem is currently breaking the ecosystem. OpenCover started shipping sample projects as part of their package and we are now red build territory💥
> fix: don't include tools/*.csproj when packing

- docs/input/docs/fundamentals/environment-variables.md
Make clear that also a PAT can be used as GitHub password
> Make clear that also a PAT can be used as GitHub password

- Cake.Recipe/Content/addins.cake
I'm not sure if addin reference directives are case sensitive but to be safe, I'm correcting an inconsistency.
This is also important for the AddinDiscoverer which searches `.cake` files for addin references using a case-sensitive regex.
> Fix casing inconsistency

- Cake.Recipe/Content/addins.cake
- Cake.Recipe/Content/analyzing.cake
- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/buildData.cake
Create issue report with Cake.Issues.
Replace ReSharperReports for InspectCode with Cake.Issues report. Report also contains warnings from MsBuild (if not .NET Core build).
Changes behavior of report for InspectCode that it always is created instead of only in error case and that it won't be opened in browser.
In the future this can be enhanced with further features like optional build breaking based on certain condition, linting and reporting of issues in markdown files, etc.
The newly introduced `BuildData` class might also replace `BuildParameters` in the future.
Fixes #219
> (GH-219) Create issue report with Cake.Issues

- Cake.Recipe/Content/analyzing.cake
- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/buildData.cake
Use absolute path for repository root which fixes exception during issue readin in some cases.
I've also used the `BuildData` typed context to hold the repository root path. Let me know if you prefer to have it in the BuildPaths class instead for consistency
> Use absolute path for repository root

- Cake.Recipe/Content/addins.cake
Update to Cake.Issues 0.4.0. This brings reporting of the project name for InspectCode and also only project name, instead of full path, for MSBuild issues, improving filtering and sorting experience.
> Update to Cake.Issues 0.4.0

- Cake.Recipe/Content/addins.cake
Cake.Git 0.19.0 is required to fix running Cake.Recipe with Cake.CoreCLR (https://github.com/cake-contrib/Cake_Git/issues/60)
> Update Cake.Git to 0.19.0 version

- docs/input/docs/usage/code-coverage-reports.md
due to the extra parentheses in the link to the information about portable pdb,
the link is thought to be a relative link. This PR fixes that by
removing those extra characters.
/CC @gep13
> (docs) Removed extra parentheses in link

- Cake.Recipe/Content/addins.cake
- Cake.Recipe/Content/analyzing.cake
- Cake.Recipe/Content/appveyor.cake
- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/buildData.cake
- Cake.Recipe/Content/tasks.cake
Replace issue management with [Cake.Issues.Recipe](https://cakeissues.net/docs/recipe/overview). This will bring integration with build servers (currently Azure Pipelines and AppVeyor) and pull request systems (currently Azure Repos).
`BuildData` class is now empty, but I kept it here since using it is part of #396.
Since Cake.Git already comes with Cake.Issues.Recipe it needs to be removed from Cake.Recipe.
Fixes #470
> (GH-470) Use Cake.Issues.Recipe for issue management

- Cake.Recipe/Content/build.cake
The changes in this PR forces the dotnet restore command to restore packages using the configured Debug/Release configuration.
If this is not passed in, this can cause issues when a project have conditional package restoring (like only some packages should be restored during debugging, like packages hooking into the visual studio debugger which is not needed when producing a production build).
fixes #502
> (GH-502) Set configuration during package restore

- Cake.Recipe/Content/addins.cake
- Cake.Recipe/Content/codecov.cake
- Cake.Recipe/Content/coveralls.cake
- Cake.Recipe/Content/paths.cake
- Cake.Recipe/Content/testing.cake
I decided to not fallback to the coverlet utility when a unit testing project don't have it referenced. I decided because the addin `Cake.Coverlet` unfortunately have hard-coded the calls to that utility in debug build, and can not be changed.
fixes #356
> (GH-356) Add support for generating coverage reports using coverlet

- Cake.Recipe/Content/parameters.cake
In the long run, we may wish to change out the code for detecting wether we are running on appveyor/travis/etc to get the value directly from the new build providers instead.
fixes #366
> (GH-366) Update codecov code to latest travis ci support

- Cake.Recipe/Content/appveyor.cake
- Cake.Recipe/Content/azurepipelines.cake
- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/buildProvider.cake
- Cake.Recipe/Content/localbuild.cake
- Cake.Recipe/Content/tasks.cake
- Cake.Recipe/Content/teamcity.cake
- Cake.Recipe/Content/travis-ci.cake
This pull request updates the existing build providers to use a single Task to report the different environment variables available in each CI system.
This makes it easier to add additional environment variables in the future for different providers if/when there is a need to do so.
An example of the output can be seen here: https://ci.appveyor.com/project/AdmiringWorm/cake-recipe/builds/33964080#L220 (since it won't show on the pr build without dogfooding Cake.Recipe).
/cc @gep13
> (maint) Updated build providers to have a single task for printing environment variables

- .appveyor.yml
- .editorconfig
- .gitattributes
- .gitignore
- Cake.Recipe/Content/build.cake
- build.ps1
- build.sh
- recipe.cake
- (GH-441) Update addins references
- (GH-441) Update Cake version in package.config
- (GH-533) Change to compare supported cake major-minor versions
- (maint) Dogfood current cake.recipe during building
This pull request adds a small helper that takes care of comparing the supported Cake version towards the one that the user is currently running.
This comparison helper only compares major+minor parts of the version, so users can still update patch releases without Cake.Recipe complaining.
This pull request changes the current build process to build Cake using the latest unstable source by making use of dogfooding,
this required an update of Cake version 0.33.0 and as such I merged in #442.
This can be rebased if that is desirable instead.
resolves #533
> (GH-533) Change to only compare major minor version of cake + dogfooding

- Cake.Recipe/Content/build.cake
This pull request adds a simple way to disable the throwing of an error when the version of Cake do not match the version that Cake.Recipe was built with.
This switch `--ignore-cake-version` is used without any arguments to allow this to happen, a warning will be outputted to the user that he/she is running an unsupported/untested version of Cake, but execution of the build will be allowed to continue.
resolves #536
> (GH-536) Add ability to ignore cake version when executing build

- .github/workflows/build.yaml
- Cake.Recipe/Content/buildProvider.cake
- Cake.Recipe/Content/github-actions.cake
- Cake.Recipe/Content/parameters.cake
- build.sh
This pull request adds a new build provider that will be used when running Cake.Recipe on github actions.
This build provider should be updated once Cake.Recipe supports 0.36.0+ to use Cakes included BuildSystem support.
A small basic workflow file was also added to be able to verify build isn't breaking anything on gh actions.
Unfortunately only windows could be enable until Cake.Recipe supports Cake 0.37.0+
resolves #531
/cc @gep13
> (GH-531) Implemented build provider support for github actions

- Cake.Recipe/Content/parameters.cake
Previously, it was assumed that you would always publish to Coveralls,
and the only way to prevent it was to hack the environment variable to
be something that couldn't be found.  This new parameter allows
controlling whether Coveralls should be used.  It will default to true,
since that is how things work just now.
Fixes #535
> (GH-535) Provide ability to not use Coveralls

- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/packages.cake
- Cake.Recipe/Content/parameters.cake
Previously, a build had to be completely successful before notifications
were sent to Twitter/Gitter, etc.  However, it is possible to some
publishing tasks fail, but the artifacts are still sent to their end
location, i.e NuGet.org.  In these cases, it would make sense for the
notifications to be sent, since the packages have been released.  As
such, the Teardown method has been updated to send notifications, when
it knows artifacts have been sent successfully.
Fixes #299
> (GH-299) Change how notifications are sent

- Cake.Recipe/Content/gitversion.cake
There is a slight edge case where artifacts are pushed to the wrong
GitHub release.  Rather then set milestone to MajorMinorPatch, use the
asserted SemVer version instead.
Fixes #80
> (GH-80) Set milestone to correct version number

- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/codecov.cake
- Cake.Recipe/Content/gitreleasemanager.cake
- Cake.Recipe/Content/gitter.cake
- Cake.Recipe/Content/microsoftteams.cake
- Cake.Recipe/Content/packages.cake
- Cake.Recipe/Content/parameters.cake
- Cake.Recipe/Content/twitter.cake
- recipe.cake
When you want to use something other than GitVersion to perform the
versioning of the repository, you can override the new Setup method,
and as long as you provide a BuildVersion instance, the remainder of
the code should work as expected.
Fixes #217
> (GH-217) Add ability to override versioning

- Cake.Recipe/Content/build.cake
The OutputPath property for a parsed project has been made Obsolete, and
we need to use the OutputPaths property instead.  This code isn't
particularly pretty, but it should work.
Fixes #215
> (GH-215) Move away from obsolete property

- Cake.Recipe/Content/toolsettings.cake
After this version, 5.0.1, GitVersion started shipping as a single
contained executable, which means it no longer supports running with
Mono, and as a result, Cake.Recipe won't work on Unix systems.  To
enable support on these platforms, need to pin to this specific version.
Fixes #552
> (GH-552) Use earlier version of GitVersion

- Cake.Recipe/Content/build.cake
This pull request adds the ability to use msbuild on unix platforms when the executable is available.
With a fallback to xbuild if msbuild could not be found
resolves #379
> (GH-379) Use msbuild on unix when it is available

- Cake.Recipe/Content/testing.cake
The coverage report passed to ReportGenerator on .NET Core was using the path only available when running OpenCover during the build process.
This is incorrect, and should have been the all of the files outputted by Coverlet and OpenCover.
*I did not create a issue for this, as coverlet support was first added in upcoming 2.0.0 of Cake.Recipe*
> (maint) Correct coverage file paths passed to ReportGenerator

- Cake.Recipe/Content/toolsettings.cake
The current version of codecov-exe is broken when running on windows when running builds for normal msbuild projects.
This pull request updates codecov-exe to the latest bug fix that fixes this issue.
> (GH-523) Update codecov to latest bug fix release

- Cake.Recipe/Content/addins.cake
- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/packages.cake
- Cake.Recipe/Content/setup.cake
- Cake.Recipe/Content/tasks.cake
- Cake.Recipe/Content/testing.cake
The main purpose of this pull request is to remove as much duplicated code as we can.
The achieve this the following have been done:
1. Moved all setup tasks to its own file. This was done mostly to know in which order they will be executed, in case we need to rely on them.
2. Moved ReportUnit to its own task
3. Moved ReportGenerator to its own task
4. Added a setup task for creating the minimum of common DotNetCoreMSSettings that we need.
Additionally, I updated the reference to Cake.Codecov as the current version passes invalid file path arguments to codecov-exe
> (maint) Update internals to remove duplication of code

- Cake.Recipe/Content/addins.cake
Update Cake.Issues.Recipe to 0.3.4. This brings support for parsing markdownlint log files, which is required for #240
> Update Cake.Issues.Recipe to 0.3.4

- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/parameters.cake
This pull request has the goal of preventing some of the Null Reference and Sequence is empty exceptions to happen.
I am making sure that in `parameters.cake` the branch name that gets returned from the current CI Provider is set to an empty string in the few cases that the provider returns null.
This is done to prevent the null reference exception to happen when we later checks if the branch name starts with a certain string.
I am also adding an additional check before we copy files in `build.cake` to ensure that we do not get an Empty Sequence exception, which can occur when a project file defines conditional target frameworks (there may be other cases as well).
> (maint) Prevent null-reference and sequence empty exceptions to occur

- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/paths.cake
- Cake.Recipe/Content/toolsettings.cake
This pull request replaces the already used XMLLogger with a the same BinaryLogger
that is used by Cake.Issues.MSBuild, and makes it equal to the same logging capabilities
as the implementation in pull request #575
resolves #252
> (GH-252) Change xml logger to binary logger when running msbuild

- Cake.Recipe/Content/deterministic.cake
This pull request adds a new standalone task that can be used to add the necessary references
to enable both coverlet and sourcelink and the current projects, as well as creating the
necessary workaround to make coverlet work correctly with deterministic and sourcelink builds.
resolves #571
> (GH-571) Add task to generate files/references to enable coverlet and deterministic build

- Cake.Recipe/Content/gitversion.cake
- Cake.Recipe/Content/localbuild.cake
i.e. when the repository hasn't been cloned, but rather downloaded as a
zip file.
When in this situation, default to some sensible values.
Fixes #578
> (GH-578) Support building when not using git

- Cake.Recipe/Content/appveyor.cake
- Cake.Recipe/Content/azurepipelines.cake
- Cake.Recipe/Content/buildProvider.cake
- Cake.Recipe/Content/github-actions.cake
- Cake.Recipe/Content/localbuild.cake
- Cake.Recipe/Content/parameters.cake
- Cake.Recipe/Content/teamcity.cake
- Cake.Recipe/Content/travis-ci.cake
This pull request updates the build providers to add a property that defines wether coverage reports can be pushed to codecov.io without using a token.
This is added to make it easier to detect this kind of support, and identify the support when new providers are added or when codecov-exe/codecov.io supports more CI Providers.
> (maint) Updated build providers to store codecov tokenless support

- Cake.Recipe/Content/parameters.cake
This Pull Request fixes the incorrect check for usage of a GitHub token when running GitReleaseManager.
This change makes it so that if a GitHub PAT is used, no GitHub username needs to be specified.
fixes #583
also related to issue #452
> (GH-583) Correct check for GitHub token vs password for GRM

- Cake.Recipe/Content/github-actions.cake
During a normal branch build on GitHub actions, the branch reference
is prefixed with 'refs/heads' and should be removed from reference
to get the correct branch name. This pull request makes the change
necessary by checking the tempName if it starts with that string
and remove it if it exist.
This is also considered an enhancement of the code I previously provided
to detect build providers for GitHub Actions (which is currently unreleased code).
> (GH-531) Improve branch detection on github actions

- Cake.Recipe/Content/toolsettings.cake
- Cake.Recipe/Content/wyam.cake
This is the last of the tools that can be moved to .net core.
Fixes #523
> (GH-523) Use .Net Global tool version of KuduSync

- Cake.Recipe/Content/gitreleasemanager.cake
- Cake.Recipe/Content/gitversion.cake
- docs/input/docs/usage/create-pre-release.md
- docs/input/docs/usage/creating-release.md
This allows an argument called 'create-pre-release' to be used when calling the cake build script for specifically setting the milestone to the generated SemVer version, instead of a stable version. On tagged releases this should always be the SemVer version no matter what is used.
resolves #597
> (GH-597) Add ability to select pre-release or stable release notes

- Cake.Recipe/Content/parameters.cake
- Cake.Recipe/Content/setup.cake
- Cake.Recipe/Content/toolsettings.cake
In some cases, there is no need to use the TargetFrameworkOverridePath when building .NET Full Framework using .NET Core. This is especially true if the user already references the needed reference assemblies provided by Microsoft (which will also be the default in .NET Core 5.x).
In other cases, we may resolve the wrong path to the mono library directory (especialy in cases where a custom directory is used), so allowing users to override the directory used is also useful.
resolves #598
> (GH-598) Allow users to disable or override target framework path

- Cake.Recipe/Content/parameters.cake
- docs/input/docs/usage/create-pre-release.md
- docs/input/docs/usage/creating-release.md
- recipe.cake
GitVersion now is capable of running everywhere, so let's enable it by
default.
Fixes #603
> (GH-603) Turn on GitVersion by default

- Cake.Recipe/Content/appveyor.cake
- Cake.Recipe/Content/azurepipelines.cake
- Cake.Recipe/Content/buildProvider.cake
- Cake.Recipe/Content/github-actions.cake
- Cake.Recipe/Content/gitreleasemanager.cake
- Cake.Recipe/Content/localbuild.cake
- Cake.Recipe/Content/packages.cake
- Cake.Recipe/Content/parameters.cake
- Cake.Recipe/Content/teamcity.cake
- Cake.Recipe/Content/travis-ci.cake
This will allow control over which combination of Operating System and
CI platform should be used when publishing artifacts, etc.  The default
will be AppVeyor and Windows.
Fixes #599
> (GH-599) Add preferred CI system

- Cake.Recipe/Content/parameters.cake
- Cake.Recipe/Content/setup.cake
A null exception happens when running on windows,
under cake .net core and mono not being installed.
This commit fixes that issues to only set
shouldUseFrameworkPath to true when running
on Unix.
This pr also removes the check for windows platform in the setup stage, as the only way this will run on windows is if the user have specifically set shouldUseFrameworkPath to true.
> (GH-598) Fix null exception happening on windows

- Cake.Recipe/Content/addins.cake
- Cake.Recipe/Content/analyzing.cake
Update Cake.Issues.Recipe to final version of 0.4.0, which brings support for dupFinder issues and file linking (so that file names are linked to source code if it is hosted on either GitHub or Azure Repos).
> Update to Cake.Issues.Recipe 0.4.0

- Cake.Recipe/Content/build.cake
- Cake.Recipe/Content/packages.cake
- Cake.Recipe/Content/tools.cake
- Cake.Recipe/Content/toolsettings.cake
This pull request adds the ability to run cake.recipe and push package even when no local or global nuget executable is available.
This is done by first checking if a nuget executable is available (either with the name nuget, or nuget.exe) and only restore NuGet.CommandLine if no executable was found.
fixes #626
> (GH-626) Add restoring of nuget if none is found

- Cake.Recipe/Content/tools.cake
The initial pull request that was created to allow running nuget package when nuget isn't installed, mistakenly removed continuing the execution when nuget is available.
This pull request fixes that issue, so we can have nuget packages again.﻿
> (maint) Fix action never getting called when tool already exist

- .github/workflows/build.yaml
- .vscode/settings.json
- Cake.Recipe/Content/buildPlatform.cake
- Cake.Recipe/Content/email.cake
- Cake.Recipe/Content/testing.cake
Due to a use case not being considered, trailing spaces, multiple spaces and prefixed spaces causes an exception to occur.
This pull request adds a StringSplitOptions.None to all split operations to prevent this from happening.﻿
> (maint) Add missing string split options

- Cake.Recipe/Content/credentials.cake
- Cake.Recipe/Content/environment.cake
- Cake.Recipe/Content/gitreleasemanager.cake
- Cake.Recipe/Content/parameters.cake
- docs/input/docs/fundamentals/environment-variables.md
- docs/input/docs/fundamentals/set-variable-names.md
This is being removed from GitHub itself, so we need to remove it from
Cake.Recipe as well.  The upcoming 2.0.0 is the ideal time to put this
through.
Fixes #581
> (GH-581) Remove use of Username/pass for GitHub

- docs/input/_Bottom.cshtml
- docs/input/docs/extending/modify-built-in-tasks.md
These fixes include an incorrect documentation of how to override built-in cake tasks, and a minor fix to how the GitHub button is handled.
> (docs) Minor fixes to documentation

- Cake.Recipe/Content/parameters.cake
> (GH-677) set default for WebLinkRoot as RepositoryName instead of title.

- Cake.Recipe/Content/analyzing.cake
- Cake.Recipe/Content/toolsettings.cake
This will need changed once upstream support is added into Cake for the
new way of executing DupFinder and InspectCode on non Windows machines.
Fixes #673
> (GH-673) Use .Net Global Tool for ReSharper Tools

- Cake.Recipe/Content/addins.cake
Update Cake.Issues.Recipe to 0.4.1, which updates to [Cake.Issues 0.9.1](https://github.com/cake-contrib/Cake.Issues/releases/tag/0.9.1) and [Cake.Issues.PullRequests.AzureDevOps 0.9.1](https://github.com/cake-contrib/Cake.Issues.PullRequests.AzureDevOps/releases/tag/0.9.1).
> Update Cake.Issues.Recipe to 0.4.1

- Cake.Recipe/Content/addins.cake
Update to [Cake.Issues.Recipe 0.4.2](https://github.com/cake-contrib/Cake.Issues.Recipe/releases/tag/0.4.2) bringing support for GitHub Actions.
> Update Cake.Issues.Recipe to 0.4.2

- Cake.Recipe/Content/addins.cake
Update Cake.Issues.Recipe to 0.4.3. Same feature set as 0.4.2, but uses Cake.Issues.PullRequests.GitHubActions, instead of implementation in Cake.Issues.Recipe itself.
> Update Cake.Issues.Recipe to 0.4.3

- Cake.Recipe/Content/setup.cake
Add rule URL resolver for CakeContrib-Guidelines rules. This allows to have a link to the rule documentation in the issue report.
> Add rule URL resolver for CakeContrib-Guidelines

- Cake.Recipe/Content/credentials.cake
- Cake.Recipe/Content/environment.cake
- docs/input/docs/fundamentals/environment-variables.md
- docs/input/docs/fundamentals/set-variable-names.md
- docs/input/docs/upgrading/1.x-to-2.x.md
- docs/input/docs/usage/create-pre-release.md
- docs/input/docs/usage/creating-release.md
to ensure no conflicts between gh-cli and Cake.Recipe.
Also, when evaluating the GITHUB_PAT the following
environment-variables are considered (only if GITHUB_PAT is empty):
* GH_TOKEN
* GITHUB_TOKEN
This ensures backwards compatibility with previous versions of Cake.Recipe
and also conforms a bit more to gh-cli, as the two are used there, too.
fixes #700
> (GH-700) renamed GITHUB_TOKEN to GITHUB_PAT

- Cake.Recipe/Content/packages.cake
- Cake.Recipe/Content/toolsettings.cake
- docs/input/docs/fundamentals/set-tool-settings.md
This allows duplicate NuGet packages to not throw
any errors when there is a duplicate package version
in the upstream repository, and instead allow the
build to continue without any failures
closes #775
> (GH-775) Add ability to skip duplicate package version during push

- docs/input/docs/ci-systems/azure.md
and explained why setting branches explicitly
could be needed.
I kind of don't like the "we" wording here, but I had no better idea. Suggestions welcome 😉 
fixes #767
> (GH-767) added a trigger section to Azure DevOps

- Cake.Recipe/Content/packages.cake
The current logic of pushing chocolatey packages uses the current preferred build platform to decide when to push the package.
Unfortunately, at a later part this is further restricted to only push those packages on Windows platforms.
This eventually causes an issue where the packages are never pushed if the preferred build platform os is set to something other than ﻿Windows.
This pull request fixes that issues by always trying to push chocolatey when the current OS is Windows, even if the preferred build platform os is set to something else.
fixes #801
> (GH-801) Update to push Chocolatey packages on Windows platforms

- Cake.Recipe/Content/teamcity.cake
replaces the current System.NullReferenceException
with something a bit more meaningful.
The error now looks like this:
fixes #793
> (GH-793) error when vcsroot.branch is missing

- Source/Cake.Recipe/Content/addins.cake
This pull request was manually created because Cake.AddinDiscoverer triggered AbuseException before it was able to submit this PR.
Resolves #828
> Update Cake.Gitter reference from 1.0.1 to 1.0.2

- Source/Cake.Recipe/Cake.Recipe.csproj
> (#847) Bump CakeContrib.Guidelines to v1.1.1 to update NuGet package icon

- docs/input/docs/ci-systems/github.md
in the documentation for GitHub. Also added hints to dependabot and
renovate.
fixes #845
> (#845) specified the full versions of GitHub actions

- Source/Cake.Recipe/Content/analyzing.cake
- Source/Cake.Recipe/Content/toolsettings.cake
to 2021.2.1, to support ToolsVersion 17 (VS 2022)
I've had [the workaround](https://github.com/cake-contrib/Cake.Recipe/issues/862#issuecomment-908270457) in place in some builds for a while now, without any problems. I see no harm in bumping JetBrains.ReSharper.CommandLineTools
fixes #862
> (#862) bumped JetBrains.ReSharper.CommandLineTools

- Source/Cake.Recipe/Content/build.cake
- Source/Cake.Recipe/Content/packages.cake
- Source/Cake.Recipe/Content/tools.cake
so that only tools from the tools folder are being used
and not some random tool installed on the system.
Also modified resolution of nuget so that only `nuget.exe` is searched and never `nuget`.
The reasoning being, that the required tool (NuGet.Commandline)
will never install a tool `nuget` but always only install `nuget.exe`.
fixes #854
> (#854) modified resolution of RequireToolNotRegistered

- .config/dotnet-tools.json
- Source/Cake.Recipe/Content/addins.cake
- Source/Cake.Recipe/Content/analyzing.cake
- Source/Cake.Recipe/Content/build.cake
This will allow us to push out a 3.0.0 which will support Cake 1.x, and
then we can look to support Cake 2.x.
Relates to #762
> (#762) Update Cake and Cake.Issues.Recipe

- .github/workflows/build.yaml
- Source/Cake.Recipe/Content/configuration.cake
Rather than use the hack that was being used, make use of the Arguments
alias which has now been created.
Fixes #723
> (#723) Use alias for getting Arguments

- Source/Cake.Recipe/Content/toolsettings.cake
This was used for testing purposes, but the official version can now be
used.
Fixes #803
> (#803) Remove usage of MyGet feed

- .config/dotnet-tools.json
- Source/Cake.Recipe/Content/addins.cake
- Source/Cake.Recipe/Content/buildProvider.cake
- Source/Cake.Recipe/Content/setup.cake
Use the built in aliases that are part of Spectre.Console.
Fixes #877
> (#877) Remove usage of Cake.Figlet

- Source/Cake.Recipe/Content/addins.cake
By removing the manual references to MimeKit, MailKit, MimeTypesMap,
and Cake.Email.Common and replacing them by adding "loaddependencies=true"
to the Cake.Email reference.
fixes #915
> (#915) fixed sending of mails

- Source/Cake.Recipe/Content/build.cake
- Source/Cake.Recipe/Content/parameters.cake
So now, when StandardMessage, TwitterMessage, GitterMessage,
or MicrosoftTeamsMessage are changed, the parameters
which are sent to string.Format can also be changed by
settings MessageParameters.
The default for MessageParameters is equal to the "old" value,
so this change is compatible with "old" settings where the
messages were either changed or unchanged.
fixes #897
> (#897) Added a configuration for the MessageParameters

- Source/Cake.Recipe/Content/toolsettings.cake
Correctly set `SetToolSettings.SkipDuplicatePackages` if `skipDuplicatePackages` is passed to the static `SetToolSettings` method.
Fixes #1009
> (GH-1009) Consider SetToolSettings.skipDuplicatePackages

- Source/Cake.Recipe/Content/toolsettings.cake
fixes #988 
supersedes #989 
fixes #990 
supersedes #991
> (#988)(#990) update GitReleasemanager and -.Tool to 0.18.0

- Source/Cake.Recipe/Content/addins.cake
- Source/Cake.Recipe/Content/appveyor.cake
- Source/Cake.Recipe/Content/azurepipelines.cake
- Source/Cake.Recipe/Content/buildProvider.cake
- Source/Cake.Recipe/Content/codecov.cake
- Source/Cake.Recipe/Content/credentials.cake
- Source/Cake.Recipe/Content/github-actions.cake
- Source/Cake.Recipe/Content/localbuild.cake
- Source/Cake.Recipe/Content/parameters.cake
- Source/Cake.Recipe/Content/teamcity.cake
- Source/Cake.Recipe/Content/toolsettings.cake
- Source/Cake.Recipe/Content/travis-ci.cake
- docs/input/docs/fundamentals/environment-variables.md
- docs/input/docs/upgrading/3.x-to-4.x.md
Codecov no longer officially supports tokenless coverage uploads.
While it may work in rare cases, it is more appropriate
for us to remove this support completely.
This PR makes these necessary changes to remove the support.
Additionally, this PR also updates the Cake.Codecov library to v2.0.0 and replaces the unofficial Codecov-exe project with the CodecovUploader that embeds the official Codecov CLI executables.
- fixes #999 
- fixes #1001
> (#1001) Remove tokenless support for Codecov

- Source/Cake.Recipe/Content/parameters.cake
- Source/Cake.Recipe/Content/tasks.cake
- Source/Cake.Recipe/Content/transifex.cake
The old transifex-client that was previously supported has stopped working some time ago, the new executable that replaces it is not fully compatibly with how we set up the api token when connecting to transifex.
This new executable also adds support for new global arguments where the token can be specified with, and as such this PR updates cake.recipe to be compatible with this new executable.
The changes are made directly here in Cake.Recipe instead of in Cake.Transifex for the global argument, as it won't be backported to be supported on older versions of Cake.
fixes #979
> (#979) Add support for new transifex client

- Source/Cake.Recipe/Content/analyzing.cake
Latest InspectCode version generates a SARIF file by default. Enforce to write an XML file which Cake.Issues can parse.
Once we've updated to Cake Issues 3.x we can use the available SARIF parser.
> Output InspectCode result in XML format
